name: platform_timezone
description: A flutter plugin for getting the platform timezone.
version: 1.0.1
homepage: https://github.com/tzh-goon/platform_timezone

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.tzhgoon.platform_timezone
    pluginClass: PlatformTimezonePlugin
